### ISSUE TITLE
Improper skew interpretation when the file has a byte offset

### ISSUE THREAD

**Issue by cx1111** [bemoody/wfdb#13]
If a file has a byte offset, and one of the channels has a skew field, instead of removing the leading samples of that channel, the samples are displayed and t = 0 is set to the first sample of the skewed channel. Other channels have their first samples duplicated backwards.

**Comment by bemoody** [comment]
This should finally be fixed with commits 69859e74056a4d5a8db2ea95a9780e9690e8c48f and 5e44e817576d5076fb85975cb90606fa2f1d3554.
