### ISSUE TITLE
WDF2MAT error  out when header file does not have record length

### ISSUE THREAD

**Issue by ikarosilva** [bemoody/wfdb#2]
In some records where the record length is not specified,  WFDBDESC works fine, but WFDB2MAT does not generate a output file (no *.mat), outputting the following message:

wfdb2mat -r 1003
wfdb2mat: no output
 Use the -f and -t options to specify time limits
(or type 'wfdb2mat -h' for help)

**Comment by bemoody** [comment]
This was fixed in commit 48dbc9ef73b95cbb0293f2acfeb9d43ac1fea64f.
